# Generated by Django 4.2.6 on 2023-11-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_remove_product_digital_alter_product_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
