# Generated by Django 4.2.6 on 2023-11-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_product_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="author",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
