# Generated by Django 4.2.6 on 2024-02-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product", name="detaljnije", field=models.URLField(blank=True),
        ),
    ]
