# Generated by Django 4.2.6 on 2024-02-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_product_detaljnije"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="detaljnije",
            field=models.SlugField(max_length=40),
        ),
    ]
