# Generated by Django 4.0 on 2024-06-06 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_detaljnije'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='detaljnije',
        ),
    ]
